name: Update gist with most used programming languages
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  language-box:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10
          run_install: true

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Update
        run: pnpm dlx github-lang-box@2
        env:
          GH_USERNAME: shkwon98
          GIST_ID: f68abf4ba95f16bed9ef56d1d124bda1
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # You can also use hardcoded values instead of variables
          # EXCLUDE: Jupyter Notebook,CSS,TeX,PHP
          # EXCLUDE_REPO: username/repo1,username/repo2
          # EXCLUDE: ${{ vars.EXCLUDE }}
          # EXCLUDE_REPO: ${{ vars.EXCLUDE_REPO }}
          # DESCRIPTION: Your custom description
